stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install_and_build:
  stage: build
  image: node:latest
  script:
    - npm install --prefer-offline --no-audit
    - npm run build
  artifacts:
    paths:
      - dist/
  when: manual

upload_to_s3:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest3
  tags:
    - aws
  script:
    - env
    - aws s3 cp dist/ "s3://$S3_BUCKET_NAME/path/to/destination/" --recursive
  dependencies:
    - install_and_build